# Generated by Django 4.2.7 on 2023-12-06 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_employee_client_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('thumbline', models.CharField(max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=500)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('project_detatils', models.TextField(blank=True, max_length=1000, null=True)),
                ('project_status', models.CharField(choices=[('PENDING', 'Pending'), ('UI/UX_WORKING', 'UI/UX_Working'), ('IN_DEVELOPMENT', 'IN_Development'), ('IN_TESTING', 'IN_Testing'), ('IN_DEPLOYMENT', 'IN_Deployment'), ('COMPLETE', 'Complete')], default='PENDING', max_length=80)),
                ('ProjectType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.projecttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('developer', models.ManyToManyField(blank=True, null=True, to='user.employee')),
                ('project_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.client')),
            ],
        ),
    ]
