# Generated by Django 4.2.7 on 2023-12-06 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_title', models.CharField(max_length=255)),
                ('meet_link', models.URLField()),
                ('meet_docs', models.FileField(blank=True, null=True, upload_to='Meeting_Docs/')),
                ('meet_detatils', models.TextField(blank=True, max_length=1000, null=True)),
                ('meet_time', models.DateTimeField()),
                ('meet_attender', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
